title: Category
description: Category of the Forum
icon: category
primary: name
readOnly: false
history: false
properties:
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
  titles:
    type: relation
    title: titles
    description: Description of the titles input
    options:
      position: bottom
    relationType: onetomany
    dependent: false
    bucket:
      resourceFieldRef:
        schemaName: spica-forum-asset-title-bucket
  surveys:
    type: relation
    title: surveys
    description: Description of the surveys input
    options:
      position: bottom
    relationType: onetomany
    dependent: false
    bucket:
      resourceFieldRef:
        schemaName: spica-forum-asset-survey-bucket
  popularity:
    type: number
    title: popularity
    description: Description of the popularity input
    options:
      position: bottom
    minimum: 0
    maximum: 100
acl:
  write: true==true
  read: true==true
order: 6
