_id: 67ed3b61b8c681002bdc53f7
title: Users
description: Describe your new bucket
icon: view_stream
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
  description:
    type: textarea
    title: description
    description: Description of the row
    options:
      position: right
acl:
  write: true==true
  read: true==true
order: 1
